# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [20]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [58]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y ,train_size=0.80, test_size=0.20)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [60]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
# Your code here:

# instantiate learning model
data_lr = LinearRegression()

# fitting the model
data_lr.fit(X_train, y_train)

# predict the response
y_test_predict_lr = data_lr.predict(X_test)



## 3. Calculate and print R-squared for both the training and the testing set.

In [61]:
from sklearn.metrics import mean_squared_error, r2_score

r2_test = r2_score(y_test, y_test_predict_lr)

r2_train = r2_score(y_train, data_lr.predict(X_train))

print('\nr2_test', r2_test, '\nr2_test',r2_train )


r2_test 0.6584036081581839 
r2_test 0.7530239378846676


## 4. Calculate and print mean squared error for both the training and the testing set.

In [62]:
MSE_LR_train = mean_squared_error(y_train, data_lr.predict(X_train))
MSE_LR_test = mean_squared_error(y_test, y_test_predict_lr)

print('\nMSE_train', MSE_LR_train, '\nMSE_test', MSE_LR_test)


MSE_train 20.49181782298752 
MSE_test 30.43292794369121


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [64]:
from sklearn.metrics import mean_absolute_error
MAE_LR_train = mean_absolute_error(y_train, data_lr.predict(X_train))
MAE_LR_test = mean_absolute_error(y_test, y_test_predict_lr)
print('\nMAE_train',MAE_LR_train, '\nMAE_test', MAE_LR_test)


MAE_train 3.1819920576345626 
MAE_test 3.5481547752308256


## Classification Model Evaluation

In [65]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X,y ,train_size=0.80, test_size=0.20)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120, 1), (30, 1))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [67]:
from sklearn.linear_model import LogisticRegression

# instantiate learning model
data_logr = LogisticRegression()

# fitting the model
data_logr.fit(X_train, y_train)

# predict the response
y_test_predict_logr = data_logr.predict(X_test)

/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [69]:
from sklearn.metrics import accuracy_score

AC_test = accuracy_score(y_test, y_test_predict_logr)
AC_train = accuracy_score(y_train, data_logr.predict(X_train))
print('\naccuracy_score_train', AC_train, '\naccuracy_score_test', AC_test)


accuracy_score_train 0.9416666666666667 
accuracy_score_test 0.8666666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [70]:
from sklearn.metrics import balanced_accuracy_score

BAC_test = balanced_accuracy_score(y_test, y_test_predict_logr)
BAC_train = balanced_accuracy_score(y_train, data_logr.predict(X_train))

print('\nbalanced_accuracy_score_train', BAC_train, '\nbalanced_accuracy_score_test', BAC_test)


balanced_accuracy_score_train 0.9333333333333332 
balanced_accuracy_score_test 0.9111111111111111


## 10. Calculate and print the precision score for both the training and the testing set.

In [71]:
from sklearn.metrics import precision_score


PS_test = precision_score(y_test, y_test_predict_logr, average=None) 
PS_train = precision_score(y_train, data_logr.predict(X_train), average=None) 

print('\nprecision_score_train', PS_train, '\nprecision_score_test', PS_test)


precision_score_train [1.         1.         0.85416667] 
precision_score_test [1.         1.         0.69230769]


## 11. Calculate and print the recall score for both the training and the testing set.

In [73]:
from sklearn.metrics import recall_score

RS_test = recall_score(y_test, y_test_predict_logr, average=None) 
RS_train = recall_score(y_train, data_logr.predict(X_train), average=None) 

print('\nrecall_score_train', RS_train, '\nrecall_score_test', RS_test)


recall_score_train [1.  0.8 1. ] 
recall_score_test [1.         0.73333333 1.        ]


## 12. Calculate and print the F1 score for both the training and the testing set.

In [74]:
from sklearn.metrics import f1_score

F1S_test = f1_score(y_test, y_test_predict_logr, average=None) 
F1S_train = f1_score(y_train, data_logr.predict(X_train), average=None) 

print('\nF1_score_train', F1S_train, '\nF1_score_test', F1S_test)


F1_score_train [1.         0.88888889 0.92134831] 
F1_score_test [1.         0.84615385 0.81818182]


## 13. Generate confusion matrices for both the training and the testing set.

In [75]:
from sklearn.metrics import confusion_matrix

cm_train = confusion_matrix(y_train, data_logr.predict(X_train))
    
print('\nconfusion_matrix_train:\n', cm_train)


confusion_matrix_train:
 [[44  0  0]
 [ 0 28  7]
 [ 0  0 41]]


In [76]:
# Compute confusion matrix
cm_test = confusion_matrix(y_test, y_test_predict_logr)
    
print('\nconfusion_matrix_test:\n', cm_test)


confusion_matrix_test:
 [[ 6  0  0]
 [ 0 11  4]
 [ 0  0  9]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.